### ISSUE TITLE
1 Hexagonal architecture

### ISSUE THREAD

**Issue by fabriziomoscon** [Dysproz/ports-db-microservices#2]
90poe enterprise software requires us to apply specific design principles. In short these are DDD, Solid, clean code.
To practically implement those ideas we follow what some call hexagonal architecture, however if you are not familiar with it, I believe DDD can be achieved with other structure.

Please provide a PR with the changes you propose to your code to achieve separation of concerns via DDD and solid.

**Comment by Dysproz** [comment]
@fabriziomoscon I've created a PR which implements hexagonal architecture into existing code.
Let me know if that's a good implementation of that architecture.

I guess that was the biggest issue to address. I'll continue with other issues in further PRs
