### ISSUE TITLE
5 Makefile

### ISSUE THREAD

**Issue by fabriziomoscon** [Dysproz/ports-db-microservices#6]
Please organise your makefile in a way that a colleague without talking to you, can start working independently with the repo:
- unit_test
- run
- protogen
- docker?
- lint?
- etc

**Comment by Dysproz** [comment]
@fabriziomoscon I've added a Makefile in PR #11. Let me know if you'd like to add there any other targets.

**Comment by Dysproz** [comment]
I've also added GitHub workflow that'll run build, test and lint with every new PR.
